# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT022 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.2/gocd-cli_0.2.2_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "01a13bdeea2a1532caabe7c8ae4fbcc2e50c3e2f33a6e5b6808b93f8d973fa33"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.2/gocd-cli_0.2.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "72dc5574eb0cfcce02d58e7b7ed33685e3af7c277aa8bdc7c8d39fe27b343c75"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.2/gocd-cli_0.2.2_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "5eec1592831cefb5d1fcaa49c4517985f6db6ac49ed76190d9584136505b507d"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.2/gocd-cli_0.2.2_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "387423a4a2659b4186779502853eb2e4fb4fa2204e4bb44d02b41f6a120be02f"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.2/gocd-cli_0.2.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "4b1fd50180513b354f665bcf463363223eec544924aa65329fd7d31988f9c73a"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
