# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT030 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.0/gocd-cli_0.3.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c562e0c373111acc7711ada31aa3fca755d3309d553c84c8e07dfc5fdf1a255f"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.0/gocd-cli_0.3.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7dbb2e3bd7c4fc770fa844f1533d85a21ca4b3b68f3ec3271603c125e315ce9a"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.0/gocd-cli_0.3.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "1482206d8c0ca1116cb9d3c3ff0926fdd8218cea86eccc463c4356163d5a46d2"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.0/gocd-cli_0.3.0_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "9bf27e64f7f101c6e91032561ef2287b2f3ed142fd9e51b838e19ffb158d5921"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.0/gocd-cli_0.3.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "97cabc0ec12ff88d679709aea2a1cb7284328ae6b7cc35d61398c31d4921de39"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
