# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT023 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.3/gocd-cli_0.2.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b184be778ea5fea150293f02759fe574af75a1f93673cf10ec2368b06b14a43c"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.3/gocd-cli_0.2.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "395bffa6b7e4fa0662dc5bd7321f837024bf8401845f5872d5b4461b6dddcde3"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.3/gocd-cli_0.2.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "2332d25188c45b0b312ee82bb3ae1dc16beab0978c507241f658f5384bf58081"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.3/gocd-cli_0.2.3_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "feaa7d986e39f23c0625f5492e6c4fcf99b049ab76bf1e8d9459b6dd0f218b99"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.3/gocd-cli_0.2.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "cff4af086d4fc61071dcafed057c0d86c94d71465d4cb7b00fdbe5cd5d722e74"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
