# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCli < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.8/gocd-cli_0.2.8_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b15422bb6a8b6958110f0d471074d8e73946e5cc67ecdd5adbc5f964980edf78"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.8/gocd-cli_0.2.8_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f9247202341736820870fefd8692e79aab0153565d241dc8820fc312ffb5fff"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.8/gocd-cli_0.2.8_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "d253bd85cef85ecde74219201922cef7011552dab7ac5509aeade03d4c39b53d"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.8/gocd-cli_0.2.8_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "917bc05fd7f715550b67ee651c22f7a549894cdc004ec77502b86ef4a01dc8c7"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.8/gocd-cli_0.2.8_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "0c54ea1333025e45a7df2b16a961593398846844ec288d93007a5df8e7c8ec7d"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
