# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT025 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.5/gocd-cli_0.2.5_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f18ad83292f97b018393ce3b40bb543391bb951a467d113f8d3bdcd9ae2132e1"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.5/gocd-cli_0.2.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f6d05b2d3f7d2d41c37b20f2330a7641757f8a9a165c9fda1c268e4ca60a35eb"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.5/gocd-cli_0.2.5_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "2e33a4c045a05566e3499586e30fd6d8438f3d13f0e4dfbb76e2cf820c7314dd"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.5/gocd-cli_0.2.5_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "415632c59be94b4c164322e5da7d65f70b0cebffc8d536408fdd0ca93193eb9c"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.5/gocd-cli_0.2.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "6cb3eefb7c0348d478352a7581e4db5055a19a19c0386ef0dc50bbdbfb6dd775"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
