# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCli < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.7/gocd-cli_0.2.7_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f168f035c61f99268b49281fec796fb0c4692a16044c4a2d76f13dbb39b40dbe"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.7/gocd-cli_0.2.7_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dbebd5658d25fa973b5a6fd72bf015204e755dd273cf60b7665117b66ae51bde"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.7/gocd-cli_0.2.7_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "6f979d587d1d80a2fecf9fc38281e7e453797e20466109f6a3cd3f0298b41226"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.7/gocd-cli_0.2.7_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "a956fa9606e1becfbb9862d49fef1d39f4404ec3b52acd19bc9d76a8446ae234"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.7/gocd-cli_0.2.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "e2f5b98457db20133fbcf106620431e5f1ee31682cb521c742cf491675cbd1b6"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
