# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT031 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.1/gocd-cli_0.3.1_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2ac4d5092f41e853d57aeefdae7eb0c189786d3002a3704d4939db1a3b84c616"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.1/gocd-cli_0.3.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "cfe4d45fcabcc2a6fd7289bedc969a6a935301cfaca093ccbbf6d07d1249e030"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.1/gocd-cli_0.3.1_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "68f3798f7c9ff9b47b2a8a9d68c78d5ad88544dcb7d1e2be145675f43c04c9ee"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.1/gocd-cli_0.3.1_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "7195f7bce76e62c33072f957b7677e3caceb47b5509a30829b17f3655c3250e1"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.3.1/gocd-cli_0.3.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "daba5ea737b533e88ebc1ada2325d087b444d57b88570eabc620a5bd6f75e36a"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
