# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT026 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.6/gocd-cli_0.2.6_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0caddf09699963ce2f6b8993f1c790613b0eaee3c70a8a619e19b80856e5c05b"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.6/gocd-cli_0.2.6_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f16ecb20867c3b114bb5f4843502a308d2464a5d7206a2e02eadd5788aad7fe6"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.6/gocd-cli_0.2.6_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "0e6ae26b550f1ccca79839af76233a7eac58c9db605e5e69e15ea118235f9b99"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.6/gocd-cli_0.2.6_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "8c9e9c4bf4434c901ff4fc2819733e8fbe473dd2877ae95512029df480215c41"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.6/gocd-cli_0.2.6_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "0b133c20acc35f89ab4e958573bd5929d41350f8ced09cc71df1a85697bd9172"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
