# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCli < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.9/gocd-cli_0.2.9_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3af661d189267ae729cebac17278711607b076333195386c9120afe2056ee780"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.9/gocd-cli_0.2.9_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8e5efc6799d8a5fcf79fbc5da40c65e1791c0b49a946a986cea12ab3c2ca58bd"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.9/gocd-cli_0.2.9_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "8f7d1873d8a32e37fbb9428dead1a0b3ce71bf1da80d4f6ce3ff163c63bd0839"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.9/gocd-cli_0.2.9_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "38a46371e7e26c4faefdc49f990276b46c6decae6244282e7e18a0b2a8624e9d"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.9/gocd-cli_0.2.9_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f97bd3d7a816892aecd26725df94493d4a5921cc037a6e0d7d39f0d233f0ca76"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
