# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GocdCliAT024 < Formula
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/gocd-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.4/gocd-cli_0.2.4_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b7c44666f088c2aa554c0dc9ef5a6b92afb7085fd511110cdee842a5328cc542"

      def install
        bin.install "gocd-cli"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.4/gocd-cli_0.2.4_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "126b0cddd133970aa2bbbfce277f14c097316b497ff30217892fd7fc37238473"

      def install
        bin.install "gocd-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.4/gocd-cli_0.2.4_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "21ee045dbdb3862eb711424c8ea4ea599f6c9d0c2e9ae83111d1e4635ca79fd7"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.4/gocd-cli_0.2.4_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "d9e8859eb3a228ca64b06ae34148e8c18dcc35c9f7ee16e3175542efce141ed9"

        def install
          bin.install "gocd-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/gocd-cli/releases/download/v0.2.4/gocd-cli_0.2.4_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "4dff6c0a2caa430a8bcd3b68103e5a4b894e4b20d336b105099a30465018f741"

        def install
          bin.install "gocd-cli"
        end
      end
    end
  end
end
