# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmDiffSummary < Formula
  desc "helm-diff-summary summarizes helm diff output into a concise Terraform-style deployment plan"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.2/helm-diff-summary_0.0.2_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2a7ed9f2b5d9dae4b5c7f78d7bb50ea316b935bd1b75166205e4000bd31941a9"

      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.2/helm-diff-summary_0.0.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5309205c11e8b4aa8bd69b0dc0047fe02ba57ece952611b23e4004b2c412f2f7"

      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.2/helm-diff-summary_0.0.2_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c616317fd9b16f1a903246849c941a806ec74bd076d58ca1dd1f4b4fb4345503"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.2/helm-diff-summary_0.0.2_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "bf5f07dc11ffc96e5c58d2d141e1e39ad2cd1f20b603adfccf8dd6d42127b8cc"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.2/helm-diff-summary_0.0.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fbb723c3ae639717bcb2eca1cc0af69e669ca8fd7b62eef1018d062908bea9f0"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
  end
end
