# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-diff-summary@0.0.1" do
  name "helm-diff-summary@0.0.1"
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-diff-summary@0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_x86_64.tar.gz"
      sha256 "70c11c0c8b749a4448860049877c205255d36a1e2154e910569c9ed687ffc590"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_arm64.tar.gz"
      sha256 "24d39b05511ea6db5945237f9df0ae8e16c190f0d8e213c755053ecabdd7454a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_x86_64.tar.gz"
      sha256 "14880aa0f157b749715cf34aafa28470eedf105561d4bc0c3100f11a28734777"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_arm64.tar.gz"
      sha256 "7a65711dc7de1ef85e41036a07259d77f1a48ba7f9a8e1a58fae8ff7647ec0d7"
    end
  end

  # No zap stanza required
end
