# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmDiffSummaryAT001 < Formula
  desc "helm-diff-summary summarizes helm diff output into a concise Terraform-style deployment plan"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.1/helm-diff-summary_0.0.1_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f667eedbe399f0bfa58e7165da6ccc6e4ad2fb6711f1be0165c96ecb2ac3c632"

      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.1/helm-diff-summary_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "120b4fc3c2fa07e256256df2fe8edb83396200d7ae8fa6ccff01a8a93f4386b1"

      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.1/helm-diff-summary_0.0.1_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "73ffa260440244271ba0730cd641188677740068cf2bc6521af9ffb5a378047c"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.1/helm-diff-summary_0.0.1_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "fc05dbe1fc77b547c00ca49608d5b569d85f8929c51efb89b509598bd95935fd"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v0.0.1/helm-diff-summary_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "302f89f125b26cdd887734315bfc4e16a9f51a4afd3b544e75423fe05f0fcc5d"
      define_method(:install) do
        bin.install "helm-diff-summary"
      end
    end
  end
end
