# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-diff-summary" do
  name "helm-diff-summary"
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-diff-summary"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_x86_64.tar.gz"
      sha256 "9aa8d52b6f73dd9a8868eba259dcd893642dfa0ddec050a07283d5d46acc8c74"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_arm64.tar.gz"
      sha256 "b2d5ebab57185cdbf558fcb94ba1edc61c7802f58ff6800180ba00ca04d79196"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_x86_64.tar.gz"
      sha256 "0ca03c66a4a15519280452950569c457e453ea09ee628d65b5c7d48a5ef97ad7"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_arm64.tar.gz"
      sha256 "5b22cc93fbe50a2ee75a146176cc147f3919b001dde584d8f7819ca34a061c53"
    end
  end

  # No zap stanza required
end
