# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-diff-summary@0.0.1" do
  name "helm-diff-summary@0.0.1"
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-diff-summary@0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_x86_64.tar.gz"
      sha256 "0be170b0a9b55416e120137e83c54a603b08cc097a6fc24f5b2623ac3c022a9e"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_arm64.tar.gz"
      sha256 "d31de5e6f34c5f5b1b7d9f856c6d812a013d50ea43b2cd9929f0c0f09dd975d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_x86_64.tar.gz"
      sha256 "df9477661ef1374b1e8d8c99ab7680b42079e268f502e3f18fb4ce47207e2818"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_arm64.tar.gz"
      sha256 "93fd53e552a218f264b3fcafcf4669c8b921de79be5e66569e72940ee7c08786"
    end
  end

  # No zap stanza required
end
