# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-diff-summary" do
  name "helm-diff-summary"
  desc "A command-line tool for interacting with GoCD"
  homepage "https://github.com/nikhilsbhat/helm-diff-summary"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-diff-summary"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_x86_64.tar.gz"
      sha256 "c7903e1a87ecb98d6823d319f95b53bcc214aaad2a33430da33247fff8d487ad"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_darwin_arm64.tar.gz"
      sha256 "39dbc13f90e081f453d787e6083c4c13b121c7389da39efa6bc066a817a4b82c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_x86_64.tar.gz"
      sha256 "db1c2d2605f2577d3b40e499138773172658d1e0df3c7a171fbcddf11dc790ce"
    end
    on_arm do
      url "https://github.com/nikhilsbhat/helm-diff-summary/releases/download/v#{version}/helm-diff-summary_#{version}_linux_arm64.tar.gz"
      sha256 "4eef494350b8c493f9ed043e7e14dda779ac6af4f21ad622516811207096b6bd"
    end
  end

  # No zap stanza required
end
