# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkerdCheckerAT002 < Formula
  desc "A tool designed to assist in analysing the output generated by the Linkerd check command"
  homepage "https://github.com/nikhilsbhat/linkerd-checker"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/linkerd-checker/releases/download/v0.0.2/linkerd-checker_0.0.2_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "564989fb1005d892b1296bdce1d5a1cbb5244bc3730e976489df0c982d83e024"

      def install
        bin.install "linkerd-checker"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/linkerd-checker/releases/download/v0.0.2/linkerd-checker_0.0.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f709bfcdc5a55416b5a131bb6584872c645160bce6a31ea48c7ae0b605a0f95"

      def install
        bin.install "linkerd-checker"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/linkerd-checker/releases/download/v0.0.2/linkerd-checker_0.0.2_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "b0acb94696e215a855340579dd75aa8a152c99d9eff224fe44fafaea67d25bf5"

        def install
          bin.install "linkerd-checker"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/linkerd-checker/releases/download/v0.0.2/linkerd-checker_0.0.2_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "4dda1ecc99e99f78feacb9235910f5470e7dd1e35a54462b4907cf68faeef771"

        def install
          bin.install "linkerd-checker"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/linkerd-checker/releases/download/v0.0.2/linkerd-checker_0.0.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "50ea46e1f7e41b04092793826ebc3e4d24f949d89b02a241f9b6efde20468723"

        def install
          bin.install "linkerd-checker"
        end
      end
    end
  end
end
