# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TraefikAdmissionController < Formula
  desc "Kubernetes validating admission webhook for Traefik that prevents invalid Ingress and Traefik CRDs from being deployed."
  homepage "https://github.com/nikhilsbhat/traefik-admission-controller"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "da015f7fe164a2bff7e741699cc670ddf1a977d3a105a1441f323176e7a7816b"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "54f68bf152a1947e37cb4405d731225d118205be1289fa2f8728252e445d2e2c"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3331a3516b820923dfca4e2fe77b4fa261bfac690ab293544f1356238fa4785f"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "90e14479633d9aa1ac1c2dc06384fc0f7bc35b5b3af23f0afb08f36c3cfc70b6"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b5d647a0a369ec71a4847dff1108d02c5567dbabd36f9002eea4e09265c54ca0"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end
end
