# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TraefikAdmissionControllerAT003 < Formula
  desc "Kubernetes validating admission webhook for Traefik that prevents invalid Ingress and Traefik CRDs from being deployed."
  homepage "https://github.com/nikhilsbhat/traefik-admission-controller"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "bf51877643aaace13c7517ab2929d67bcb97abb8fe0396fd71f8c56d477afa44"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b708e8f99a79dd893fd94dd2a41e7afae486cd4f5a4abbaabdda90d0961deb79"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cfd034733144e2dc37c0404c12c18556f0c5b28dc2119b763c028f13f265ecdb"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "3cf51b1441ad42ef5354a19fbee352d5ace6dad4280c53478f7bdf048ec815d5"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f70f0bda2017b042ecb45510b37a51f3da1d6f1e533e08b872c6b4a64eb8238"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end
end
