# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TraefikAdmissionControllerAT003 < Formula
  desc "Kubernetes validating admission webhook for Traefik that prevents invalid Ingress and Traefik CRDs from being deployed."
  homepage "https://github.com/nikhilsbhat/traefik-admission-controller"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e344ce060128e1383fac74df6e8d85217b3a9100a48f162243a38c48e9b9e708"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d3049855687f918e0e9a06a31ee60e2c1923763731d968bcd0ecdd348761c428"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8bb3dc2e95160f9f4f2b6c2cb9b3dcab80569b930aad4122abbc8e9576c1e439"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "657985124f581348cdafe424d3053ab469573b8f597c25849695059f340d3306"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6b47c00d867c539165cbf3628dc591e6ac25719a3fbb271ca3013cab5939a194"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end
end
