# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TraefikAdmissionControllerAT003 < Formula
  desc "Kubernetes validating admission webhook for Traefik that prevents invalid Ingress and Traefik CRDs from being deployed."
  homepage "https://github.com/nikhilsbhat/traefik-admission-controller"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d6447d7a799354d62dd051707d8a74f253ffa37df4c6c8c22c93276775e90044"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b77fcb53b4c0fe46da6e7f3197880546a1cd53da5c13808f651bccc6a2fca0d5"

      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "81f87e0b2d69357d3ddbb03a892eb359a3be56f263bff659741300f84fbe3d96"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "8cb9ab89f581d84497b537ba48aa1bde8884f32fb3045c3a4e843a689670ad98"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/traefik-admission-controller/releases/download/v0.0.3/traefik-admission-controller_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b6aa6253ae76fd4ac6c7656af09efb9909315bafc0c20b11f1e7a81158a541a"
      define_method(:install) do
        bin.install "traefik-admission-controller"
      end
    end
  end
end
