# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamll < Formula
  desc "A utility that allows importing YAML files as libraries, similar to how programming languages manage dependencies"
  homepage "https://github.com/nikhilsbhat/yamll"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.3/yamll_0.0.3_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6225cf93df1623e24792c4a3aef4c5a39b4cee0ed08e8678ab8c8fa0d50a3ded"

      def install
        bin.install "yamll"
      end
    end
    on_arm do
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.3/yamll_0.0.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c9f6d9a5932a1f75bb9d2f031307260bfac2f6f084692d98e397a8bfa5d0a537"

      def install
        bin.install "yamll"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.3/yamll_0.0.3_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "3af2818dc590d9f75e8da7377b9c57c2961afb69fc8786c5a7ba0332b43aa73c"

        def install
          bin.install "yamll"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.3/yamll_0.0.3_linux_arm.tar.gz", using: CurlDownloadStrategy
        sha256 "db15ba7e8eae315558b97b0514bef0531f040dbc1f16604e52c0d6f1e0ba5d86"

        def install
          bin.install "yamll"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.3/yamll_0.0.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "9667f15063a98f9186a981dce082ab1e01ee98bf6081fdc196eb055032f80c9d"

        def install
          bin.install "yamll"
        end
      end
    end
  end
end
