# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamll < Formula
  desc "YAML dependency manager for importing, merging, tracing, linting, and locking shared config files."
  homepage "https://github.com/nikhilsbhat/yamll"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.5/yamll_0.0.5_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f13a55b1169cd0ff978311d620460cf70790679566f707dd8a65dce4f43acd9b"

      define_method(:install) do
        bin.install "yamll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.5/yamll_0.0.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "360b31c6589241493fe50a83935a5c8c97f2d9c4b3fa9d287f4ebdf8d4af256c"

      define_method(:install) do
        bin.install "yamll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.5/yamll_0.0.5_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f866f99a9ada8c7656584c3641f7747bcaccaedbf794ed2fb1670684a6e56ee4"
      define_method(:install) do
        bin.install "yamll"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.5/yamll_0.0.5_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "47ef241b70f5d98871df1a470e0c016e46652a64ac5bc1987ebef348131be54d"
      define_method(:install) do
        bin.install "yamll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhilsbhat/yamll/releases/download/v0.0.5/yamll_0.0.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "77217c1aecd7c6ac1cc63a8e694b80ab011b96941affb0a3358292bc79f05757"
      define_method(:install) do
        bin.install "yamll"
      end
    end
  end
end
